=== lumen-apps/map-data/building.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Building GeoJSON Feature",
  "type": "object",
  "required": [
    "type",
    "id",
    "geometry",
    "properties"
  ],
  "properties": {
    "type": {
      "type": "string",
      "enum": [
        "Feature"
      ]
    },
    "id": {
      "type": "string"
    },
    "geometry": {
      "type": "object",
      "required": [
        "type",
        "coordinates"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "Point"
          ]
        },
        "coordinates": {
          "type": "array",
          "minItems": 2,
          "maxItems": 2,
          "items": {
            "type": "number"
          }
        }
      }
    },
    "properties": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      }
    }
  }
}

=== lumen-apps/map-data/s-maria-maggiore.json
{
  "type": "Feature",
  "id": "HXSYRxph9yhcwDv0zlOz",
  "geometry": {
    "type": "Point",
    "coordinates": [
      12.498795824404862,
      41.897433909568555
    ]
  },
  "properties": {
    "name": "S. Maria Maggiore",
    "description": "Basilika in Rom. Berühmte Papstbasilika aus dem 5. Jh., bekannt für römische Mosaike und vergoldete Decke."
  }
}

=== lumen-apps/map-data/data/buildings/kathedrale-st-gallen.json
{
  "type": "Feature",
  "id": "mYJODMHXbfkH61CLEdPH",
  "geometry": {
    "type": "Point",
    "coordinates": [
      9.376435381320684,
      47.423106577633135
    ]
  },
  "properties": {
    "name": "Kathedrale St. Gallen",
    "description": "Kathedrale des Bistums St. Gallen in St. Gallen. Prächtige katholische Barockkirche mit 68 m hohen Doppeltürmen aus dem 18. Jh. im UNESCO-Erbe Stiftsbezirk."
  }
}

=== lumen-apps/map-data/petersdom.json
{
  "type": "Feature",
  "id": "3blnQm7Un6VjSEo4hryk",
  "geometry": {
    "type": "Point",
    "coordinates": [
      12.45492321686002,
      41.90217630889452
    ]
  },
  "properties": {
    "name": "Petersdom",
    "description": "Basilika im Vatikanstaat. Kirche aus der Spätrenaissance von Architekten wie Michelangelo mit Platz für bis zu 20.000 Gläubige."
  }
}

=== lumen-apps/map-data/data/buildings/liebfrauenkirche.json
{
  "type": "Feature",
  "id": "SzcPwdoRZ1vEbPHIu7x2",
  "geometry": {
    "type": "Point",
    "coordinates": [
      8.545092283056569,
      47.379535461642675
    ]
  },
  "properties": {
    "name": "Liebfrauenkirche",
    "description": "Katholische Kirche in Zürich. Nach dem Vorbild römischer Basiliken erbaute Kirche des späten 19. Jh. mit Glockenturm und Innenraum mit Säulen."
  }
}
